### ISSUE TITLE
for pull_request  GITHUB_REF_NAME doesn't contains actual branch name

### ISSUE THREAD

**Issue by jupe** [FranzDiebold/github-env-vars-action#19]
If job is triggered using `pull_request` there is no actual branch available in `GITHUB_REF_NAME`. This looks a bit issue in GitHub context side since there is no clear variable where to get branch name regardless how job is triggered. Maybe branch name extracting should be separate variable that works also for pull_requests.

```
gitHub.ref: "refs/pull/844/merg
head_ref: "my-branch",
GITHUB_REF_SLUG: refs-pull-844-merge
GITHUB_REF_NAME: 844/merge
GITHUB_REF_NAME_SLUG: 844-merge
```

**Comment by FranzDiebold** [comment]
Hi @jupe ,
thanks for your feedback!
You're right, `GITHUB_REF_NAME` is not set for event type `pull_request` by GitHub.

That's why I *improved* `github-env-vars-action` in version [v1.3.0](https://github.com/FranzDiebold/github-env-vars-action/releases/tag/v1.3.0) 📦 to solve this issue: There's now a new environment variable `GITHUB_BRANCH_NAME` exactly for this use case! 💪 It contains the branch name for both event types `push` and `pull_request`.

Have fun using `github-env-vars-action` and give it a ⭐.
